# Inverse of a Square Matrix

The inverse of a square matrix is one of the most important ideas in linear algebra because it tells us when a transformation can be reversed.

In machine learning, we often apply transformations to data:

- rotate data
- scale data
- project data
- mix features
- solve systems of equations
- estimate model parameters
- undo normalization or whitening
* analyze whether information is lost

The inverse matrix answers one powerful question:

    “After applying this matrix transformation, can I get the original data back?”

If yes, the matrix is invertible.
If no, the matrix is singular, meaning some information was destroyed.

## Simple Definition

For a square matrix A, its inverse is written as: $A^{-1}$

It satisfies:

$$
A^{-1}A = AA^{-1} = I
$$

where I is the identity matrix. The identity matrix is like the number 1 in multiplication:

$$
5 \times \frac{1}{5} = 1
$$

Similarly:

$$
A \times A^{-1} = I
$$

So, the inverse matrix is like the matrix version of division.

But important point:

Matrix division does not really exist like normal number division.
Instead, we multiply by the inverse.

For numbers:

$$
2x = 10
$$

We solve by dividing by 2:

$$
x = \frac{10}{2} = 5
$$

For matrices:

$$
Ax = b
$$

We solve by multiplying both sides by $A^{-1}$:

$$
x = A^{-1}b
$$

## Intuition: What Does a Matrix Do?

A matrix is not just a table of numbers. A matrix represents a transformation.

For example, a matrix can:

- stretch a vector
- rotate a vector
- flip a vector
- shear a vector
- mix multiple features together
- compress data into a lower-quality representation

Suppose matrix A transforms vector x into vector b:

$$
Ax = b
$$

This means: A took the original vector x and converted it into b.
Now, if we want to recover the original x, we need another matrix that undoes what A did.

That matrix is:

$$
A^{-1}
$$

So:

$$
A^{-1}b = x
$$

Meaning:

The inverse matrix reverses the transformation.


## Very Simple Example

Suppose:

$$
A =
\begin{bmatrix}
2 & 0 \\
0 & 3
\end{bmatrix}
$$

This matrix scales:

- x-axis by 2
- y-axis by 3

If we apply it to a vector:

$$
x =
\begin{bmatrix}
4 \\
5
\end{bmatrix}
$$

Then:

$$
Ax =
\begin{bmatrix}
2 & 0 \\
0 & 3
\end{bmatrix}
\begin{bmatrix}
4 \\
5
\end{bmatrix}
=
\begin{bmatrix}
8 \\
15
\end{bmatrix}
$$

So the original vector [4, 5] became [8, 15].

To reverse it, we need to divide the first coordinate by 2 and the second coordinate by 3.

So:

$$

A^{-1}
=
\begin{bmatrix}
1/2 & 0 \\
0 & 1/3
\end{bmatrix}
$$

Now:

$$
A^{-1}
\begin{bmatrix}
8 \\
15
\end{bmatrix}
=
\begin{bmatrix}
4 \\
5
\end{bmatrix}
$$

That is the core idea.

In [8]:
import torch

a = torch.tensor([[2, 0], [0, 3]], dtype=torch.float32)
b = torch.tensor([4, 5], dtype=torch.float32)
c = a @ b

print(c)

# inverse of a matrix
a_inv = torch.inverse(a)
print(a_inv)
a_inv @ c

tensor([ 8., 15.])
tensor([[0.5000, 0.0000],
        [0.0000, 0.3333]])


tensor([4., 5.])

## Why Square Matrix?

Only a square matrix can have a true inverse. A square matrix has the same number of rows and columns:

$$
n \times n
$$

Examples:

$$
2 \times 2,\quad 3 \times 3,\quad 768 \times 768
$$

Why square? Because an inverse means:

    Input dimension and output dimension are the same, and the transformation can be reversed exactly.

For example:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

This is a $2 \times 3$ matrix.

It maps a 3D vector into 2D. That means it compresses 3 dimensions into 2 dimensions. Information is lost.

So we cannot fully recover the original 3D vector. That is why non-square matrices do not have a normal inverse.

They can have special forms like:

- left inverse
- right inverse
- pseudo-inverse

But not a regular inverse.

## Invertible vs Singular Matrix

A matrix is invertible if its inverse exists. A matrix is singular if its inverse does not exist.

### Invertible Matrix

An invertible matrix is one where the transformation does not destroy information.

Example:

$$
A =
\begin{bmatrix}
2 & 0 \\
0 & 3
\end{bmatrix}
$$

This only stretches the space. Nothing collapses. So we can reverse it.

### Singular Matrix

A singular matrix destroys information.

Example:

$$
A =
\begin{bmatrix}
1 & 2 \\
2 & 4
\end{bmatrix}
$$

The second row is just 2 times the first row. So the rows are linearly dependent. This matrix does not contain two independent directions.

It collapses 2D information into something lower-dimensional. So it cannot be reversed.

## The Deep Intuition: Inverse Means “No Information Lost”

This is the idea you should never forget: A matrix has an inverse only if it does not collapse space.

Imagine a 2D sheet of paper.

A matrix transformation can:

Case 1: Stretch the paper

Still reversible.

You can shrink it back.

Invertible.

Case 2: Rotate the paper

Still reversible.

You can rotate it back.

Invertible.

Case 3: Squash the whole paper into a line

Not reversible.

Many different points now become the same point.

Singular.

Case 4: Squash everything into zero

Totally not reversible.

All information is destroyed.

Singular.

So:

Invertible matrix = transformation can be undone.
Singular matrix = transformation lost information.


## Why This Matters in Linear Algebra

The inverse connects many core linear algebra concepts:

### Linear Systems

For:

$$
Ax = b
$$

If $A^{-1}$ exists:

$$
x = A^{-1}b
$$

So the system has a unique solution.

### Rank

A square matrix is invertible if:

$$
rank(A) = n
$$

That means all rows and columns are linearly independent.

### Pivots

If a matrix has a pivot in every row and every column, it is invertible.

### Determinant

A matrix is invertible if:

$$
\det(A) \neq 0
$$

If:

$$
\det(A) = 0
$$

then the matrix is singular.

### Null Space

A matrix is invertible if:

$$
Ax = 0
$$

has only the trivial solution:

x = 0

If there is any non-zero vector x such that:

Ax = 0

then the matrix destroyed that vector, so it is not invertible.

## Computing Inverse Using Gauss-Jordan Elimination

Suppose:

$$
A =
\begin{bmatrix}
2 & 1 \\
1 & 1
\end{bmatrix}
$$
We start with:

$$
[A | I]
=
\left[
\begin{array}{cc|cc}
2 & 1 & 1 & 0 \\
1 & 1 & 0 & 1
\end{array}
\right]
$$

Goal:

$$
[I | A^{-1}]
$$

After Gauss-Jordan elimination, we get:

$$
\left[
\begin{array}{cc|cc}
1 & 0 & 1 & -1 \\
0 & 1 & -1 & 2
\end{array}
\right]
$$

So:

$$
A^{-1}
=
\begin{bmatrix}
1 & -1 \\
-1 & 2
\end{bmatrix}
$$

Check:

$$
AA^{-1}
=
\begin{bmatrix}
2 & 1 \\
1 & 1
\end{bmatrix}
\begin{bmatrix}
1 & -1 \\
-1 & 2
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
$$

So the inverse is correct.


In [11]:
import torch
A = torch.tensor([
    [2.0, 1.0],
    [1.0, 1.0]
])
A_inv = torch.linalg.inv(A)
print("A:")
print(A)
print("\nA inverse:")
print(A_inv)
print("\nA @ A_inv:")
print(A @ A_inv)


x = torch.linalg.solve(A, b)
x

A:
tensor([[2., 1.],
        [1., 1.]])

A inverse:
tensor([[ 1., -1.],
        [-1.,  2.]])

A @ A_inv:
tensor([[1., 0.],
        [0., 1.]])


tensor([-1.,  6.])

But in real machine learning code, we usually avoid explicitly computing the inverse.

Instead of this:

x = torch.linalg.inv(A) @ b

we prefer:

x = torch.linalg.solve(A, b)

Why?

Because solving directly is:

- faster
- more stable
- less prone to numerical errors

## Why Inverse Matters in Machine Learning

Matrix inverse appears in many ML algorithms, especially classical ML and optimization.

### Linear Regression

In linear regression, we want to learn weights w:

$$
Xw = y
$$

Here:

 X is the feature matrix
 w is the weight vector
 y is the target vector

The closed-form solution is:

$$
w = (X^TX)^{-1}X^Ty
$$

This is called the normal equation.

Meaning:

We use the inverse of X^TX to directly solve for the best weights.

In [13]:
X = torch.tensor([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4]
], dtype=float)
y = torch.tensor([2, 3, 4, 5], dtype=float)
w = torch.linalg.inv(X.T @ X) @ X.T @ y
print(w)

w = torch.linalg.solve(X.T @ X, X.T @ y)
w

tensor([1.0000, 1.0000], dtype=torch.float64)


tensor([1.0000, 1.0000], dtype=torch.float64)

## Why Inverse Matters in Deep Learning

In deep learning, we do not usually compute matrix inverse directly during normal neural network training. But the concept is still extremely important.

It appears in:

- optimization
- second-order methods
- covariance matrices
- whitening
- normalization
- attention analysis
- invertible neural networks
- normalizing flows
- Hessian-based methods
- numerical stability
- representation learning

## Inverse in Optimization

Gradient descent updates parameters like this:

$$
w_{new} = w - \eta \nabla L(w)
$$

This uses only first-order gradient information. But Newton’s method uses second-order curvature:

$$
w_{new} = w - H^{-1}\nabla L(w)
$$

Here:

- H is the Hessian matrix
- $H^{-1}$ is the inverse Hessian
- $\nabla L(w)$ is the gradient

The Hessian tells us the curvature of the loss surface. The inverse Hessian helps rescale the gradient direction based on curvature.

Intuition:

Gradient tells you which direction goes downhill.
Hessian inverse tells you how much to trust that direction in each dimension.

In deep learning, full Hessian inverse is usually too expensive because models have millions or billions of parameters.

But approximations are used in:

- L-BFGS
- K-FAC
- natural gradient descent
- second-order optimization
- uncertainty estimation

## Inverse in Covariance Matrices

In statistics and ML, covariance matrices are very important. A covariance matrix tells us how features move together.

For example, if we have features:

- height
- weight
- age

The covariance matrix tells us whether these features are correlated.

The inverse covariance matrix is used in:

- Gaussian distributions
- Mahalanobis distance
- anomaly detection
- Bayesian models
- Gaussian processes
- discriminant analysis

The multivariate Gaussian formula contains:

$$
\Sigma^{-1}
$$

where $\Sigma$ is the covariance matrix.

The term:

$$
(x - \mu)^T \Sigma^{-1} (x - \mu)
$$

is the Mahalanobis distance.It measures distance while considering feature correlations.

### Important ML Example: Mahalanobis Distance

Euclidean distance treats every feature equally. But in ML, features may be correlated.

Suppose two users have embeddings. Euclidean distance says:

$$
distance = ||x - y||
$$

But Mahalanobis distance says:

$$
distance = \sqrt{(x-y)^T \Sigma^{-1}(x-y)}
$$

Here, $\Sigma^{-1}$ adjusts the distance based on feature covariance.

This is useful in:

- anomaly detection
- embedding comparison
- recommender systems
- clustering
- fraud detection
- face recognition
- metric learning


In [15]:
x = torch.tensor([2, 3], dtype=float)
mu = torch.tensor([0, 0], dtype=float)
cov = torch.tensor([
    [2, 0.5],
    [0.5, 1]
], dtype=float)
cov_inv = torch.linalg.inv(cov)
mahalanobis_sq = (x - mu).T @ cov_inv @ (x - mu)
mahalanobis = torch.sqrt(mahalanobis_sq)
print(mahalanobis)

tensor(3.0237, dtype=torch.float64)


The inverse covariance helps us measure distance more intelligently.

## Inverse in Data Whitening

Whitening transforms data so that:

-    features become uncorrelated
- variance becomes 1
- covariance matrix becomes identity

This is useful in:

- PCA
- preprocessing
- optimization
- signal processing
- representation learning

The goal is:

$$
X_{white} = X \Sigma^{-1/2}
$$

Here we use something related to the inverse of covariance. After whitening:

$$
Cov(X_{white}) = I
$$

Meaning:

The data has been transformed so every direction has equal variance. This makes optimization easier because the loss surface becomes less stretched.

## Inverse in Neural Networks

A normal neural network layer is:

$
y = Wx + b
$

Here, W is a weight matrix.

If W is square and invertible, then we could recover x from y:

$$
x = W^{-1}(y - b)
$$

But most neural network layers are not designed to be invertible.

For example:

Input: 768 dimensions
Hidden layer: 256 dimensions

This compresses 768 dimensions into 256 dimensions.

Information is lost.

No true inverse exists.

That is why typical neural networks are not reversible.

However, some special architectures are designed to be invertible:

- normalizing flows
- invertible residual networks
- NICE
- RealNVP
- Glow

These models are used in generative modeling because they allow exact probability calculation.

## Inverse and Embeddings

This is very important for your recommender-system thinking.

Suppose an item embedding model maps item text into a vector:

"title + description" → 768-dimensional embedding

This transformation is usually not invertible.

Why?

Because many different texts can map to similar embeddings.

For example:

"cheap hotel in Lahore"
"affordable room near Lahore"
"budget accommodation Pakistan"

These may produce similar vectors.

Can we recover the exact original text from the embedding?

No.

So the embedding process is not truly invertible.

That means embeddings preserve semantic information, but they lose exact original information.

This is a powerful intuition:

Embeddings are useful because they compress meaning.
But because they compress, they are not perfectly reversible.

## Inverse and Recommender Systems

In recommender systems, matrix inverse appears in several places.

### Matrix Factorization

Suppose we have user-item interaction matrix:

R

We factorize it as:

$$
R \approx UV^T
$$

where:

U = user embeddings
V = item embeddings

In ALS, we solve for user vectors while fixing item vectors.

The update often looks like:

$$
u = (V^TV + \lambda I)^{-1}V^Tr
$$

Here:

- V is item embedding matrix
- r is user interaction vector
- \lambda I is regularization
- inverse helps solve optimal user vector

This is a direct use of matrix inverse in recommender systems.

### Regularization Makes Matrix Invertible

In ALS or ridge regression, we add:

$$
\lambda I
$$

to make the matrix more stable:

$$
X^TX + \lambda I
$$

This helps avoid singularity.

Why?

Because if features are highly correlated, $X^TX$ may be singular or nearly singular.

Adding $\lambda I$ improves invertibility.

This is one reason regularization is mathematically powerful.


## Why We Avoid Explicit Inverse in Production ML

Even though matrix inverse is theoretically important, in production ML code we usually avoid:

$$
A_inv = np.linalg.inv(A)
x = A_inv @ b
$$

Instead, we use:

x = np.linalg.solve(A, b)

Because computing inverse explicitly can be:

- slower
- numerically unstable
- memory expensive
- unnecessary

The better mental model:

Use inverse to understand the math.
Use solve to implement it in real systems.


## Invertibility Check

A square matrix is invertible if any of these equivalent conditions are true:

Condition 1: Full Rank

$$
rank(A) = n
$$

All rows and columns are independent.

Condition 2: Non-Zero Determinant

$$
det(A) \neq 0
$$

Condition 3: Pivot in Every Row

Gauss elimination gives pivot in every row.

Condition 4: Null Space Has Only Zero Vector

$$  
Ax = 0
$$

has only:

$$
x = 0
$$

Condition 5: Columns Span Full Space

The columns of A span $\mathbb{R}^n$.


In [1]:
import torch

A = torch.tensor([
    [1, 2],
    [2, 4]
], dtype=float)

rank = torch.linalg.matrix_rank(A)
det = torch.linalg.det(A)
print("Rank:", rank)
print("Determinant:", det)
if rank == A.shape[0]:
    print("Matrix is invertible")
else:
    print("Matrix is singular")

Rank: tensor(1)
Determinant: tensor(-0., dtype=torch.float64)
Matrix is singular



## Diagonal Dominance Trick

Your course notes mention a very useful trick:

A matrix is strictly diagonally dominant if:

$$
|a_{ii}| > \sum_{j \neq i} |a_{ij}|
$$

Meaning:

In every row, the diagonal value is bigger than the sum of all other values in that row.

Example:

$$
A =
\begin{bmatrix}
3 & 1 & 1 \\
1 & 3 & 1 \\
1 & 1 & 3
\end{bmatrix}

$$
Check first row:

$$
|3| > |1| + |1|
$$

$$
3 > 2
$$

Second row:

$$
|1| > |3| + |1|
$$

$$
1 > 4
$$

Third row:

3 > 2

So this matrix is strictly diagonally dominant.

Strict diagonal dominance guarantees invertibility.

But important:

If a matrix is not diagonally dominant, it can still be invertible.

So diagonal dominance is a sufficient condition, not a necessary condition.

Meaning:

- diagonally dominant ⇒ invertible
- not diagonally dominant ⇒ maybe invertible, maybe not

## Properties of Inverses

### Property 1: Inverse Is Unique

If a matrix has an inverse, it has only one inverse.

There cannot be two different inverse matrices.

Why?

Suppose both B and C are inverses of A.

Then:

AB = I

and:

AC = I

We can show:

B = C

So inverse is unique.


### Property 2: Inverse of Transpose

If A is invertible:

$$
(A^T)^{-1} = (A^{-1})^T
$$

Meaning:

If you transpose a matrix and then invert it, that equals inverting first and then transposing.

This matters in ML because transposes appear everywhere:

$$
X^TX
$$

$$
W^TW
$$

$$
QK^T
$$


### Property 3: Inverse of Product

For two invertible matrices A and B:

$$
(AB)^{-1} = B^{-1}A^{-1}
$$

Notice the order reverses.

This is very important.

Why does the order reverse?

Suppose:

A = put on socks
B = put on shoes

Then:

$$
AB
$$

means we applied two operations.

To undo them:

1. remove shoes
2. remove socks

So the reverse operation is:

$$
B^{-1}A^{-1}
$$

The last operation is undone first.

That is why:

$$
(AB)^{-1} \neq A^{-1}B^{-1}
$$

Usually, the correct formula is:

$$
(AB)^{-1} = B^{-1}A^{-1}
$$


## Why Inverse Matters for Feature Engineering

Suppose you normalize data:

$$
x_{norm} = \frac{x - \mu}{\sigma}
$$

To recover original data:

$$
x = x_{norm}\sigma + \mu
$$

This is not exactly matrix inverse, but it is the same idea:

Apply transformation, then apply inverse transformation to recover original values.

For multivariate normalization, scaling and whitening may use matrices.

If the transformation matrix is invertible, we can recover the original data.

If not, we cannot.

This matters in:

- PCA
- dimensionality reduction
- autoencoders
- feature compression
- image reconstruction
- embeddings
- representation learning

## Inverse and PCA

PCA transforms data into principal components.

If PCA keeps all components, the transformation is reversible.

If PCA drops some components, it is not perfectly reversible.

Example:

Original data: 100 dimensions
PCA output: 10 dimensions

This compresses 100D into 10D.

Information is lost.

No exact inverse exists.

But PCA can approximately reconstruct the original data.

This teaches a key ML idea:

Dimensionality reduction usually destroys some information, so exact inverse is impossible.

## Inverse and Autoencoders

Autoencoders also relate to this idea.

An encoder maps:

$$
x \rightarrow z
$$

A decoder maps:

$$
z \rightarrow \hat{x}
$$

If z has lower dimension than x, exact inverse is usually impossible.

Example:

Input image: 784 dimensions
Latent vector: 32 dimensions

The encoder compresses the image.

The decoder tries to reconstruct it.

But because information was compressed, reconstruction may not be perfect.

So:

Autoencoders learn an approximate inverse, not a true mathematical inverse.


## Inverse in Attention and Transformers

In standard transformer attention, we compute:

$$
Attention(Q, K, V) = softmax\left(\frac{QK^T}{\sqrt{d}}\right)V
$$

There is no direct inverse here.

But inverse-related concepts matter indirectly:

- rank of attention matrices
- whether representations collapse
- whether transformations preserve information
- whether projection matrices reduce dimension
- whether hidden states remain expressive

For example, if a projection matrix maps:

768 dimensions → 64 dimensions

then it loses information.

It is not invertible.

But if it maps:

768 dimensions → 768 dimensions

and has full rank, it may be invertible.

This helps you reason about whether a layer preserves or compresses information.



## Common Mistake: Thinking Every Square Matrix Has an Inverse

Not every square matrix has an inverse.

Example:

$$
A =
\begin{bmatrix}
1 & 2 \\
2 & 4
\end{bmatrix}
$$

This is square, but not invertible.

Why?

Because row 2 is just:

$$
2 \times row_1
$$

So it has only one independent row.

Rank is 1, not 2.

So inverse does not exist.


## Common Mistake: Using Inverse in Code Everywhere

Many beginners write:

weights = np.linalg.inv(X.T @ X) @ X.T @ y

This is mathematically correct but numerically not ideal.

Better:

weights = np.linalg.solve(X.T @ X, X.T @ y)

Even better for many ML cases:

weights = np.linalg.lstsq(X, y, rcond=None)[0]

In PyTorch:

weights = torch.linalg.lstsq(X, y).solution

Reason:

Explicit inverse magnifies numerical errors.

## Common Mistake: Forgetting Order Reversal

Wrong:

$$
(AB)^{-1} = A^{-1}B^{-1}
$$

Correct:

$$
(AB)^{-1} = B^{-1}A^{-1}
$$

Memory trick:

To undo putting on socks and shoes, remove shoes first, then socks.


## The Best Mental Model

Remember this forever:

A matrix is a machine that transforms vectors.
The inverse matrix is the machine that runs the process backward.
If the original machine destroyed information, no inverse machine can recover it.

That is the whole idea.

### Final Interview-Style Explanation

A matrix inverse is the matrix that reverses the effect of another square matrix. For a matrix A, its inverse $A^{-1}$ satisfies $A^{-1}A = AA^{-1} = I$. Geometrically, an invertible matrix represents a transformation that does not collapse space or lose information. A matrix is invertible only when its rows and columns are linearly independent, its rank is full, its determinant is non-zero, and the equation Ax=0 has only the trivial solution.

In machine learning, inverses appear in solving linear systems, linear regression, ridge regression, ALS recommender systems, Gaussian models, covariance matrices, Mahalanobis distance, whitening, PCA, and second-order optimization. In deep learning, we rarely compute explicit inverses because they are expensive and numerically unstable, but the concept helps us understand whether transformations preserve or destroy information. In practice, instead of computing $A^{-1}b$, we usually solve $Ax=b$ directly using numerical solvers.

The simplest memory hook is:

If a matrix transformation can be undone, it has an inverse.
If it loses information, it is singular.