In [1]:
# !pip install torch

In [2]:
import torch
torch.__version__

'1.5.0'

In [3]:
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [4]:
A = torch.tensor([[1,2],[2,3]])
A

tensor([[1, 2],
        [2, 3]])

In [5]:
print(x.size())
print(A.size())

torch.Size([4])
torch.Size([2, 2])


In [6]:
A = torch.tensor([[1,2],[2,3],[4,5]])
print(A)
print(A.size())
A_T = A.t()
print(A_T.size())
print(A_T)

tensor([[1, 2],
        [2, 3],
        [4, 5]])
torch.Size([3, 2])
torch.Size([2, 3])
tensor([[1, 2, 4],
        [2, 3, 5]])


In [7]:
A_T

tensor([[1, 2, 4],
        [2, 3, 5]])

In [8]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])
B = torch.tensor([[2, 5], [7, 4], [4, 3]])

In [9]:
A + B

tensor([[ 3,  7],
        [10,  8],
        [ 9,  9]])

In [10]:
A+4

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [11]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])
B = torch.tensor([[2], [4]])
print(A.size())
print(B.size())
C = torch.matmul(A,B)
print(C)
print(C.size())

torch.Size([3, 2])
torch.Size([2, 1])
tensor([[10],
        [22],
        [34]])
torch.Size([3, 1])


In [12]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:
x = torch.tensor([[2.], [6.], [3.]])
print(x)
print(x.shape)
print(torch.eye(x.shape[0]))
print(torch.matmul(torch.eye(x.shape[0]), x))
# 

tensor([[2.],
        [6.],
        [3.]])
torch.Size([3, 1])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[2.],
        [6.],
        [3.]])


In [31]:
A = torch.tensor([[3., 0, 2], [2, 0, -2], [0, 1, 1]])
inverse_A = torch.inverse(A)
print(inverse_A)
print(torch.matmul(A,inverse_A))

tensor([[ 0.2000,  0.2000, -0.0000],
        [-0.2000,  0.3000,  1.0000],
        [ 0.2000, -0.3000,  0.0000]])
tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.9605e-08, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0000e+00]])
