# Matrix Factorization

Matrix factorization is a mathematical technique used to decompose a matrix into two or more matrices such that when multiplied together, they approximate the original matrix. This technique is widely used in various fields like collaborative filtering in recommendation systems, natural language processing, and dimensionality reduction.

## Why Matrix Factorization Was Invented

Matrix factorization was invented to solve several key problems:

1. **Dimensionality Reduction**: In high-dimensional datasets, matrix factorization helps reduce the number of dimensions while retaining essential information. This is crucial in tasks like image processing and natural language processing.

2. **Collaborative Filtering**: In recommendation systems, matrix factorization is used to predict user preferences for items (e.g., movies, products) by uncovering latent factors representing both users and items.

3. **Noise Reduction**: By approximating the original matrix, matrix factorization helps in removing noise and capturing underlying patterns in the data.

4. **Data Compression**: It allows for the compression of large datasets by representing them with smaller matrices.

### Problems Solved by Matrix Factorization

1. **Sparse Data**: Many real-world datasets, such as user-item ratings in recommendation systems, are sparse (contain many missing values). Matrix factorization helps in predicting the missing values.

2. **Pattern Recognition**: It helps in recognizing patterns and structures in the data that are not immediately obvious.

3. **Improved Recommendations**: By capturing latent factors, matrix factorization improves the accuracy of recommendations.

### Mathematical Explanation

Matrix factorization involves decomposing a matrix $ A $ into two matrices $ W $ and $ H $ such that $ A \approx WH $. Here is a detailed explanation:

Given a matrix $ A $ of size $ m \times n $, matrix factorization aims to find two matrices $ W $ (of size $ m \times k $) and $ H $ (of size $ k \times n $) such that:

$$ A \approx WH $$

### Objective Function

One common approach is to minimize the Frobenius norm of the difference between $ A $ and $ WH $:

$$ \min_{W, H} \| A - WH \|_F^2 $$

Where $ \| \cdot \|_F $ denotes the Frobenius norm, which is defined as:

$$ \| A - WH \|_F^2 = \sum_{i=1}^m \sum_{j=1}^n (A_{ij} - (WH)_{ij})^2 $$

#### Optimization

To find $ W $ and $ H $, we typically use optimization techniques like gradient descent. The update rules for gradient descent are:

$$ W \leftarrow W - \eta \frac{\partial}{\partial W} \| A - WH \|_F^2 $$
$$ H \leftarrow H - \eta \frac{\partial}{\partial H} \| A - WH \|_F^2 $$

Where $ \eta $ is the learning rate.

### Toy Example

Suppose we have the following matrix $ A $:

$$ A = \begin{bmatrix} 5 & 3 \\ 3 & 2 \\ 2 & 1 \\ 1 & 1 \end{bmatrix} $$

We want to factorize this into two matrices $ W $ and $ H $ such that $ A \approx WH $.

#### Code in PyTorch

Here's a simple implementation of matrix factorization in PyTorch:


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

# Toy example matrix A
A = torch.tensor([[5, 3],
                  [3, 2],
                  [2, 1],
                  [1, 1]], dtype=torch.float32)

# Dimensions
m, n = A.size()
k = 2  # Number of latent factors

# Initialize W and H with random values
W = torch.rand(m, k, requires_grad=True)
H = torch.rand(k, n, requires_grad=True)

# Define the learning rate and number of iterations
learning_rate = 0.01
num_iterations = 5000

# Define the optimizer
optimizer = optim.Adam([W, H], lr=learning_rate)

# Training loop
for iteration in range(num_iterations):
    optimizer.zero_grad()
    A_pred = torch.matmul(W, H)
    loss = torch.nn.functional.mse_loss(A_pred, A)
    loss.backward()
    optimizer.step()
    
    if (iteration+1) % 500 == 0:
        print(f"Iteration {iteration+1}, loss: {loss.item()}")

print("Original Matrix A:")
print(A)

print("\nFactorized Matrices W and H:")
print(W)
print(H)

print("\nReconstructed Matrix A from W and H:")
print(torch.matmul(W, H))

/Users/ikram.ali/miniconda3/envs/ml_notes/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Iteration 500, loss: 6.450703949667513e-05
Iteration 1000, loss: 8.83535022921933e-09
Iteration 1500, loss: 2.0268231537556858e-12
Iteration 2000, loss: 9.698908343125368e-13
Iteration 2500, loss: 5.773159728050814e-13
Iteration 3000, loss: 1.7275070263167436e-13
Iteration 3500, loss: 1.567634910770721e-13
Iteration 4000, loss: 3.019806626980426e-14
Iteration 4500, loss: 2.842170943040401e-14
Iteration 5000, loss: 1.7763568394002505e-15
Original Matrix A:
tensor([[5., 3.],
        [3., 2.],
        [2., 1.],
        [1., 1.]])

Factorized Matrices W and H:
tensor([[ 2.0369,  2.0575],
        [ 1.4867,  0.9807],
        [ 0.5502,  1.0768],
        [ 0.9365, -0.0961]], requires_grad=True)
tensor([[1.1957, 1.1052],
        [1.2464, 0.3640]], requires_grad=True)

Reconstructed Matrix A from W and H:
tensor([[5.0000, 3.0000],
        [3.0000, 2.0000],
        [2.0000, 1.0000],
        [1.0000, 1.0000]], grad_fn=<MmBackward0>)


#### Explanation of the Code

1. **Initialization**: We initialize the matrices $ W $ and $ H $ with random values.
2. **Optimization**: We use the Adam optimizer to update the values of $ W $ and $ H $.
3. **Training Loop**: In each iteration, we compute the predicted matrix $ A_{pred} $ by multiplying $ W $ and $ H $. We then compute the mean squared error loss between $ A $ and $ A_{pred} $ and perform backpropagation to update $ W $ and $ H $.

This implementation iteratively minimizes the reconstruction error, resulting in matrices $ W $ and $ H $ that approximate the original matrix $ A $.

## Eigen Decomposition

Eigen decomposition (also known as spectral decomposition) is a fundamental concept in linear algebra used to decompose a square matrix into its eigenvalues and eigenvectors. It has numerous applications in various fields such as physics, engineering, computer science, and finance.

### Why Eigen Decomposition Was Invented

Eigen decomposition was developed to solve several important problems:

1. **Understanding Matrix Behavior**: It provides insights into the properties of linear transformations represented by matrices.
2. **Diagonalization**: It simplifies matrices into a diagonal form, making many matrix operations more efficient.
3. **Solving Systems of Linear Equations**: It helps in solving differential equations and systems of linear equations.
4. **Principal Component Analysis (PCA)**: It is crucial in data reduction techniques like PCA, where eigenvectors represent principal components of the data.

### Problems Solved by Eigen Decomposition

1. **Matrix Simplification**: By decomposing a matrix into eigenvalues and eigenvectors, complex matrix operations become simpler.
2. **Data Analysis**: It is used in PCA to reduce the dimensionality of data while retaining its essential features.
3. **Stability Analysis**: In control theory and dynamical systems, it helps analyze the stability of systems.
4. **Quantum Mechanics**: It is used to solve the Schrödinger equation and understand quantum states.

### Mathematical Explanation

Given a square matrix $ A $ of size $ n \times n $, eigen decomposition involves finding a set of eigenvalues $ \lambda $ and corresponding eigenvectors $ v $ such that:

$$ Av = \lambda v $$

Where:
- $ A $ is the original matrix.
- $ \lambda $ is an eigenvalue.
- $ v $ is an eigenvector.

#### Eigen Decomposition Formula

If $ A $ is diagonalizable, it can be expressed as:

$$ A = V \Lambda V^{-1} $$

Where:
- $ V $ is a matrix whose columns are the eigenvectors of $ A $.
- $ \Lambda $ is a diagonal matrix whose diagonal elements are the eigenvalues of $ A $.
- $ V^{-1} $ is the inverse of $ V $.

### Toy Example

Consider the following matrix $ A $:

$$ A = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix} $$

We want to find the eigenvalues and eigenvectors of $ A $.

### Finding Eigenvalues

The eigenvalues are found by solving the characteristic equation:

$$ \det(A - \lambda I) = 0 $$

Where $ I $ is the identity matrix. For our matrix $ A $:

$$ A - \lambda I = \begin{bmatrix} 4 - \lambda & 1 \\ 2 & 3 - \lambda \end{bmatrix} $$

The determinant of this matrix is:

$$ (4 - \lambda)(3 - \lambda) - (2 \cdot 1) = 0 $$
$$ \lambda^2 - 7\lambda + 10 = 0 $$

Solving this quadratic equation, we get:

$$ \lambda_1 = 5, \lambda_2 = 2 $$

### Finding Eigenvectors

For each eigenvalue $ \lambda $, we solve:

$$ (A - \lambda I)v = 0 $$

For $ \lambda = 5 $:

$$ \begin{bmatrix} 4 - 5 & 1 \\ 2 & 3 - 5 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = \begin{bmatrix} -1 & 1 \\ 2 & -2 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = 0 $$

This gives us the eigenvector $ v_1 = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $.

For $ \lambda = 2 $:

$$ \begin{bmatrix} 4 - 2 & 1 \\ 2 & 3 - 2 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = \begin{bmatrix} 2 & 1 \\ 2 & 1 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = 0 $$

This gives us the eigenvector $ v_2 = \begin{bmatrix} -1 \\ 2 \end{bmatrix} $.

### Code in PyTorch
#### Explanation of the Code

1. **Initialization**: We define the matrix $ A $.
2. **Eigen Decomposition**: We use `torch.linalg.eig` to compute the eigenvalues and eigenvectors.
3. **Reconstruction**: We reconstruct the original matrix using the eigenvalues and eigenvectors to verify the decomposition.

This implementation demonstrates the process of eigen decomposition and verifies that the original matrix can be reconstructed from its eigenvalues and eigenvectors.

In [2]:
import torch

# Toy example matrix A
A = torch.tensor([[4.0, 1.0],
                  [2.0, 3.0]])

# Perform eigen decomposition
eigenvalues, eigenvectors = torch.linalg.eig(A)

print("Original Matrix A:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

# Reconstructing the matrix from eigenvalues and eigenvectors
V = eigenvectors
D = torch.diag(eigenvalues)
V_inv = torch.linalg.inv(V)

A_reconstructed = V @ D @ V_inv

print("\nReconstructed Matrix A:")
print(A_reconstructed)

Original Matrix A:
tensor([[4., 1.],
        [2., 3.]])

Eigenvalues:
tensor([5.+0.j, 2.+0.j])

Eigenvectors:
tensor([[ 0.7071+0.j, -0.4472+0.j],
        [ 0.7071+0.j,  0.8944+0.j]])

Reconstructed Matrix A:
tensor([[4.0000+0.j, 1.0000+0.j],
        [2.0000+0.j, 3.0000+0.j]])
